### ISSUE TITLE
Conan cmake error with SDL2

### ISSUE THREAD

**Issue by TheMeadTree** [PieKing1215/FallingSandSurvival#12]
I'll just post the error report for Conan here, x64 Windows, Visual Studio 2019:

-- Conan: Skipping compiler check: Declared 'compiler.toolset'
CMake Error at source_subfolder/CMakeLists.txt:12 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
-- Configuring incomplete, errors occurred!
See also "C:/Users/BigD/.conan/data/sdl2_ttf/2.0.15/bincrafters/stable/build/71b33648681346c64a4d98d9026b76188c1b1378/build_subfolder/CMakeFiles/CMakeOutput.log".
  provides a separate development package or SDK, be sure it has been
  installed.

sdl2_ttf/2.0.15@bincrafters/stable: 
WARN: sdl2_ttf/2.0.15@bincrafters/stable: requirement sdl2/2.0.9@bincrafters/stable overridden by your conanfile to sdl2/2.0.12@bincrafters/stable 
WARN: freetype/2.9.1@bincrafters/stable: requirement libpng/1.6.37@bincrafters/stable overridden by sdl2_ttf/2.0.15@bincrafters/stable to libpng/1.6.37 
WARN: freetype/2.9.1@bincrafters/stable: requirement zlib/1.2.11@conan/stable overridden by sdl2_ttf/2.0.15@bincrafters/stable to zlib/1.2.11 
WARN: sdl2_image/2.0.5@bincrafters/stable: requirement sdl2/2.0.10@bincrafters/stable overridden by your conanfile to sdl2/2.0.12@bincrafters/stable 
WARN: libtiff/4.0.9: requirement libjpeg/9d overridden by sdl2_image/2.0.5@bincrafters/stable to libjpeg/9c 
sdl2/2.0.12@bincrafters/stable: WARN: Can't update, no package in remote
libtiff/4.0.9: WARN: Can't update, no package in remote
sdl2_image/2.0.5@bincrafters/stable: WARN: Can't update, no package in remote
sdl2_ttf/2.0.15@bincrafters/stable: WARN: Package binary is corrupted, removing: 71b33648681346c64a4d98d9026b76188c1b1378
sdl2_ttf/2.0.15@bincrafters/stable: WARN: Build folder is dirty, removing it: C:\Users\BigD\.conan\data\sdl2_ttf\2.0.15\bincrafters\stable\build\71b33648681346c64a4d98d9026b76188c1b1378
sdl2_ttf/2.0.15@bincrafters/stable: ERROR: Package '71b33648681346c64a4d98d9026b76188c1b1378' build failed
sdl2_ttf/2.0.15@bincrafters/stable: WARN: Build folder C:\Users\BigD\.conan\data\sdl2_ttf\2.0.15\bincrafters\stable\build\71b33648681346c64a4d98d9026b76188c1b1378
ERROR: sdl2_ttf/2.0.15@bincrafters/stable: Error in build() method, line 82
	cmake = self._configure_cmake()
while calling '_configure_cmake', line 51
	cmake.configure(build_folder=self._build_subfolder)
	ConanException: Error 1 while executing cd C:\Users\BigD\.conan\data\sdl2_ttf\2.0.15\bincrafters\stable\build\71b33648681346c64a4d98d9026b76188c1b1378\build_subfolder && cmake -G "Visual Studio 16 2019" -A "x64" -DCONAN_LINK_RUNTIME="/MDd" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="16" -DCONAN_CXX_FLAGS="/MP16" -DCONAN_C_FLAGS="/MP16" -DCMAKE_INSTALL_PREFIX="C:\Users\BigD\.conan\data\sdl2_ttf\2.0.15\bincrafters\stable\package\71b33648681346c64a4d98d9026b76188c1b1378" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -Wno-dev -T "v142" C:\Users\BigD\.conan\data\sdl2_ttf\2.0.15\bincrafters\stable\build\71b33648681346c64a4d98d9026b76188c1b1378
Conan has returned exit code '1' while processing configuration 'Architecture: x86_64, build type: Debug, compiler toolset: v142, compiler version: 16;, runtime library: MDd'. Please check file 'C:\Users\BigD\Desktop\Folder\FallingSandSurvival\x64\Debug\.conan\conan_03a70271-a71a-41a0-b540-8034d4181eb8.log' for details.

I followed all of the install instructions as written, but something is wrong with SDL2 it seems.

**Comment by PieKing1215** [comment]
Yeah this is a problem I've had on and off for a while depending on the build configuration.
It's a problem with the actual sdl2_ttf recipe, and this finally prompted me to open an issue there (https://github.com/bincrafters/community/issues/1360)
Basically waiting on this PR which should fix it: https://github.com/bincrafters/community/pull/1363

**Comment by PieKing1215** [comment]
Ok the fix went through, though there's a couple steps you need to do to use the new sdl2_ttf version
(you can also just pull dev and rerun setup.sh and it should do these for you)
1) Switch bincrafters remote to the new repo [as explained here](https://bincrafters.readthedocs.io/en/latest/using_packages.html#adding-the-bincrafters-repository-as-a-conan-remote)
`conan remote remove bincrafters`
`conan remote add bincrafters https://bincrafters.jfrog.io/artifactory/api/conan/public-conan`
`conan config set general.revisions_enabled=1`
2) Clear sdl2_ttf cache
`conan remove sdl2_ttf -f`

... and then building it should work hopefully.
