### ISSUE TITLE
ERROR: Unable to find 'sdl_gpu/20201002@sdl_gpu/20201002' in remotes

### ISSUE THREAD

**Issue by behappyis** [PieKing1215/FallingSandSurvival#14]
Good day!

I am trying to runnning FallingSandSurvival with much trouble.

I have error in conan's processing.
"ERROR: Unable to find 'sdl_gpu/20201002@sdl_gpu/20201002' in remotes"

**Please advice conan remote url for "sdl_gpu/20201002@sdl_gpu/20201002"** 

thanks.

**Comment by PieKing1215** [comment]
Did you run the setup script?
One of the things it does is install the correct version of sdl_gpu into conan locally, since it isn't on any of the online repos.

When you run setup.sh, it should print something like "Setting up Conan sdl_gpu...", and if it's already installed it should print "Conan sdl_gpu already installed."
If it isn't installed, the script will try to install sdl_gpu and print "Successfully installed sdl_gpu into conan" or "Failed to install sdl_gpu into conan"  depending on if it had any errors.

**Comment by behappyis** [comment]
Thanks PieKing1215

I tried to running with visual studio in windows 10.
I checked setup.sh. and planed

1. download conan-sdl_gpu
2. install sed for windows.
3. run every command line( # Patches to use newer version of sdl_gpu) manually

Sorry. How about my plan?

Thanks
-------------------
    echo "Cloning github.com/sixten-hilborn/conan-sdl_gpu..."
    git clone https://github.com/sixten-hilborn/conan-sdl_gpu ./conan-sdl_gpu
    cd ./conan-sdl_gpu
    
    # Patches to use newer version of sdl_gpu
    sed -i 's/20171229/20201002/g' ./conanfile.py
    sed -i 's/143f767adf7d472f81ce890d4692ed29369aa8f3/47a3e2b2a9326c33ad6f177794705987399de8cf/g' ./conanfile.py
    sed -i 's/2.0.9/2.0.12/g' ./conanfile.py
    sed -i "s/sdl2 sdl2 sdl-2.0'/SDL2d sdl2 sdl2 sdl-2.0'/g" ./conanfile.py
    sed -i "s/sdl2 sdl2 sdl-2.0 SDL2d'/SDL2d sdl2 sdl2 sdl-2.0'/g" ./conanfile.py
    sed -i "s/SDL_gpu_INSTALL/INSTALL_LIBRARY/g" ./conanfile.py
    sed -i "s/SDL_gpu_BUILD_DEMOS/BUILD_DEMOS/g" ./conanfile.py
    sed -i "s/SDL_gpu_BUILD_SHARED/BUILD_SHARED/g" ./conanfile.py
    sed -i "s/SDL_gpu_BUILD_STATIC/BUILD_STATIC/g" ./conanfile.py
    sed -i "s/SDL_gpu_USE_SDL1/USE_SDL1/g" ./conanfile.py
    sed -i "s/SDL_gpu_DISABLE_GLES_1/DISABLE_GLES_1/g" ./conanfile.py
    conan export . sdl_gpu/20201002
-------------------

**Comment by behappyis** [comment]
Thanks

I understood sed command 
(
sed -i 's/20171229/20201002/g' ./conanfile.py
= replace  "20171229" to "20201002" in ./conanfile.py
)

and edited conanfile.py manually.
and installed sdl_gpu into conan locally successfully!

but still have some errors.
I want to fix these and play FallingSandSurvival.

```
C:\FallingSandSurvival-dev\FallingSandSurvival-dev\out\build\x64-Release\easy_profiler.lib(profile_manager.obj) : error LNK2001: unresolved external symbol __imp___std_init_once_begin_initialize 
C:\FallingSandSurvival-dev\FallingSandSurvival-dev\out\build\x64-Release\easy_profiler.lib(profile_manager.obj) : error LNK2001: unresolved external symbol __imp___std_init_once_complete 
```
