### ISSUE TITLE
Use github workflows to build an executable whenever a release is created

### ISSUE THREAD

**Issue by DonFlymoor** [PieKing1215/FallingSandSurvival#6]
GitHub workflows are very useful tools. I've used one to build and publish [voxTalkz](https://github.com/DonFlymoor/voxTalkz) to pypi, so as to be to make it easily installable with pip. I believe that it would be beneficial to be able to build Falling Sand Survival after every commit to ensure that it successfully compiles without having to compile it yourself, and to publish it to GitHub after every release so that people can easily download the executable. (Perhaps to another repository, as an artifact, or to a GitHub pages website)

https://medium.com/rkttu/write-your-github-actions-workflow-for-build-windows-application-94e5a989f477

**Comment by PieKing1215** [comment]
This is definitely something I want to do. I haven't used GitHub workflows before but I'll definitely look into it.

**Comment by DonFlymoor** [comment]
I'll try to one based on your setup script, although I'm not quite sure how to handle FMOD.

**Comment by DonFlymoor** [comment]
To upload the compiled FallingSandSurvival to a release, [this](https://github.com/actions/upload-release-asset) may help

**Comment by PieKing1215** [comment]
Ok so I think I've got it working. Whenever there's a push to `dev`, it builds and gathers all the files it needs and makes a nice zip.
For now, I have it outputting as an artifact, and it only builds Release/x64.
Example: https://github.com/PieKing1215/FallingSandSurvival/actions/runs/285352696

**Comment by DonFlymoor** [comment]
That's great! I was trying to get it working last night, but you beat me to it. You cloud also set it just to build on all pushes to make sure it builds, but then generates a release with binaries when a tag with a v* is pushed like so:
on:
  push:
    tags:
      - v*
