### ISSUE TITLE
Add list of keyboard shortcuts

### ISSUE THREAD

**Issue by DonFlymoor** [PieKing1215/FallingSandSurvival#8]
**Describe the feature you'd like**
A list of keyboard shortcuts 

**Is your feature request related to a problem? Please describe.**
This is a great looking game, but I can't really figure out how to use it... by playing around, I figured out that P put the character into the game, E destroys everything in a circular area, and C turns a cube of terrain into a falling body, but I cannot figure out how to do anything else. I would apricate a list of keyboard shortcuts in order to use all the features.

**Comment by PieKing1215** [comment]
Ok I made a wiki page: [Controls](../wiki/Controls)
There's still a lot of things that require you to change the code to access, like giving yourself other tools and using the demo world generator, but at some point I'm going to work on some more UI things so you can do them in-game.
